name: cdn-bump-version
description: Uploads version file to CDN
inputs:
  bunny-stor-hostname:
    description: Bunny SFTP Hostname
    required: true
  bunny-stor-username:
    description: Bunny SFTP Username
    required: true
  bunny-stor-password:
    description: Bunny SFTP Password
    required: true
  cf-bucket:
    description: Name of the S3 bucket
    required: true
  version:
    description: 'Version of the release'
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true

runs:
  using: composite
  steps:
    - name: Upload version file
      shell: bash
      run: |
        mkdir -p upload
        echo "${{ inputs.version }}" >> upload/version-${{ inputs.release-channel }}.txt
        sshpass -p "${{ inputs.bunny-stor-password }}" scp -r upload/ ${{ inputs.bunny-stor-username }}@${{ inputs.bunny-stor-host }}:/
