name: cdn-bump-version
description: Uploads version file to CDN
inputs:
  bunny-stor-hostname:
    description: Bunny SFTP Hostname
    required: true
  bunny-stor-username:
    description: Bunny SFTP Username
    required: true
  bunny-stor-password:
    description: Bunny SFTP Password
    required: true
  bunny-api-key:
    description: Bunny API key
    required: true
  bunny-cdn-url:
    description: Bunny pull zone base url e.g. https://firmware.openshock.org (no trailing slash)
    required: true
  version:
    description: 'Version of the release'
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true

runs:
  using: composite
  steps:
    - name: Upload version file
      shell: bash
      run: |
        mkdir -p upload
        echo "${{ inputs.version }}" >> upload/version-${{ inputs.release-channel }}.txt
        sshpass -p "${{ inputs.bunny-stor-password }}" scp -v -r upload/* ${{ inputs.bunny-stor-username }}@${{ inputs.bunny-stor-hostname }}:/

    - name: Purge CDN cache
      shell: bash
      run: |
        curl -X POST "https://api.bunny.net/purge?url=${{inputs.bunny-cdn-url}}/version-${{ inputs.release-channel }}.txt" \
          -H "Content-Type: application/json" \
          -H "AccessKey: ${{ input.bunny-api-key }}" \'