
name: build-captive-portal
description: Builds the captive portal
inputs:
  node-version:
    description: 'NodeJS runtime version to use'
    required: true
  skip-checkout:
    description: 'If true, skips checkout'
    default: false

runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    if: ${{ !inputs.skip-checkout }}
    with:
      sparse-checkout: |
        WebUI
      path: ${{ github.repository }}

  - uses: actions/setup-node@v3
    with:
      node-version: ${{ inputs.node-version }}
      cache: 'npm'
      cache-dependency-path: ./WebUI/package-lock.json

  - name: Install dependencies
    working-directory: ./WebUI
    shell: bash
    run: npm ci

  - name: Build
    working-directory: ./WebUI
    shell: bash
    run: npm run build

  - name: Upload artifacts
    uses: actions/upload-artifact@v3
    with:
      name: captive-portal
      path: WebUI/build/*
      retention-days: 1
      if-no-files-found: error
