name: 'Bug Report'
description: "Something isn't working as expected."
title: '[Bug] '
labels: ['type: bug', 'status: triage']
projects: ['OpenShock/3']

body:

  - type: markdown
    attributes:
      value: |
        # Checklist

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: |
        To prevent wasting your or our time, please fill out the below checklist before continuing.
        Thanks for understanding!
      options:
        - label: 'I checked that no other Bug Report describing my problem exists.'
          required: true
        - label: 'I am running the latest stable or prerelease firmware.'
          required: true
        - label: 'My board is on the [list of maintained boards](https://wiki.openshock.org/hardware/boards/#fully-maintained).'
          required: true
        - label: 'I accept that this issue may be closed if any of the above are found to be untrue.'
          required: true

  - type: markdown
    attributes:
      value: |
        # Board & Firmware

  - type: input
    id: board
    attributes:
      label: Board
      description: What board are you using?
      placeholder: 'E.g.: Wemos Lolin S3, Pishock 2023, ..'
    validations:
      required: True

  - type: input
    id: firmware-version
    attributes:
      label: 'Firmware version'
      description: Which firmware version did you flash?
      placeholder: 'E.g.: 1.2.4, 1.0.0-rc.4, 0.0.0-develop, ..'
    validations:
      required: true

  - type: textarea
    id: flashing-method
    attributes:
      label: 'Flashing method'
      description: Briefly describe how you flashed your firmware.
      placeholder: |
        Examples:
        - I used the web flash tool.
        - I used the downloaded flash tool.
        - I used a different tool, namely: ...
        - I ran this command: ...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # What happened?

  - type: textarea
    id: what-happened
    attributes:
      label: 'Describe what happened as precisely as possible.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # What did you expect to happen?

  - type: textarea
    id: what-did-you-expect
    attributes:
      label: 'Describe what you expected to happen instead.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Steps to reproduce

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: 'In as much detail as possible, describe the exact steps you took to make the problem appear.'
      description: |
        If we can't reproduce the problem, we won't be able to figure out how to fix it either!
        Make sure to be as precise as you can.
      placeholder: |
        For example:
        1. Connect to the OpenShock wifi network
        2. Visit `http://10.10.10.10/`
        3. Click a WiFi network
        4. Everything explodes!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Anything else?

  - type: textarea
    id: anything-else
    attributes:
      label: 'Other remarks'
    validations:
      required: false
