name: cdn-upload-version-info
description: Uploads version specific info to CDN
inputs:
  bunny-stor-hostname:
    description: Bunny SFTP Hostname
    required: true
  bunny-stor-username:
    description: Bunny SFTP Username
    required: true
  bunny-stor-password:
    description: Bunny SFTP Password
    required: true
  fw-version:
    description: Firmware version
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true
  boards:
    description: 'List of boards, separated by newlines'
    required: true

runs:
  using: composite
  steps:
    - name: Create boards.txt
      shell: bash
      run: |
        echo -e '${{ inputs.boards }}' >> boards.txt

    - name: Upload artifacts to CDN
      shell: bash
      run: |
        mkdir -p upload
        mv boards.txt upload/
        sshpass -p "${{ inputs.bunny-stor-password }}" scp -r upload/* ${{ inputs.bunny-stor-username }}@${{ inputs.bunny-stor-hostname }}:/${{ inputs.fw-version }}/${{ inputs.board }}
