name: cdn-upload-version-info
description: Uploads version specific info to CDN
inputs:
  bunny-stor-hostname:
    description: Bunny SFTP Hostname
    required: true
  bunny-stor-username:
    description: Bunny SFTP Username
    required: true
  bunny-stor-password:
    description: Bunny SFTP Password
    required: true
  fw-version:
    description: Firmware version
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true
  boards:
    description: 'List of boards, separated by newlines'
    required: true

runs:
  using: composite
  steps:

    - name: Prepare Upload Folder
      shell: bash
      run: |
        rm -rf upload/
        mkdir -p upload/

    - name: Create boards.txt
      shell: bash
      run: |
        echo -e '${{ inputs.boards }}' >> upload/boards.txt

    - name: Upload artifacts to CDN
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: "${{ inputs.bunny-stor-hostname }}"
        remote-user: "${{ inputs.bunny-stor-username }}"
        remote-password: "${{ inputs.bunny-stor-password }}"
        remote-path: "/${{ inputs.fw-version }}/${{ inputs.board }}"
        local-path: "upload"
        sync: "full"