name: build-frontend
description: Builds the frontend and uploads it as an artifact
inputs:
  node-version:
    description: 'NodeJS runtime version to use'
    required: true
  skip-checkout:
    description: 'If true, skips checkout'
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      if: ${{ !inputs.skip-checkout }}
      with:
        sparse-checkout: |
          frontend
        path: ${{ github.repository }}

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install dependencies
      working-directory: ./frontend
      shell: bash
      run: npm ci

    - name: Build
      working-directory: ./frontend
      shell: bash
      run: npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend
        path: frontend/build/*
        retention-days: 1
        if-no-files-found: error
