name: cnd-prepare
description: Prepares the CDN for firmware uploads
inputs:
  cf-account-id:
    description: Cloudflare Account ID
    required: true
  cf-access-key-id:
    description: Cloudflare Access Key ID
    required: true
  cf-secret-access-key:
    description: Cloudflare Secret Access Key
    required: true

runs:
  using: composite
  steps:
    - name: Install rclone
      shell: bash
      run: sudo apt-get install -y rclone

    - name: Configure rclone
      shell: bash
      run: |
        mkdir -p ~/.config/rclone/
        conf=~/.config/rclone/rclone.conf
        echo "[cdn]" >> $conf
        echo "type = s3" >> $conf
        echo "provider = Cloudflare" >> $conf
        echo "access_key_id = ${{ inputs.cf-access-key-id }}" >> $conf
        echo "secret_access_key = ${{ inputs.cf-secret-access-key }}" >> $conf
        echo "endpoint = https://${{ inputs.cf-account-id }}.r2.cloudflarestorage.com" >> $conf
        echo "acl = public-read" >> $conf

