name: bunny-prepare
description: Bunny rclone setup
inputs:
  bunny-stor-hostname:
    description: Bunny SFTP Hostname
    required: true
  bunny-stor-port:
    description: Bunny SFTP Port
    required: true
  bunny-stor-username:
    description: Bunny SFTP Username
    required: true
  bunny-stor-password:
    description: Bunny SFTP Password
    required: true

runs:
  using: composite
  steps:
    - name: Install rclone
      shell: bash
      run: sudo apt-get install -y rclone

    - name: Configure rclone
      shell: bash
      run: |
        mkdir -p ~/.config/rclone/
        conf=~/.config/rclone/rclone.conf
        echo "[cdn]" >> $conf
        echo "type = sftp" >> $conf
        echo "host = ${{ inputs.bunny-stor-hostname }}" >> $conf
        echo "user = ${{ inputs.bunny-stor-username }}" >> $conf
        echo "port = ${{ bunny-stor-port }}" >> $conf
        echo "password = ${{ bunny-stor-password }}" >> $conf

