name: cdn-prepare
description: Bunny sshpass and knowhosts setup
inputs:
  bunny-ssh-knownhosts:
    description: Bunny SFTP Hostname
    required: true

runs:
  using: composite
  steps:
    - name: Install sshpass
      shell: bash
      run: sudo apt-get install -y sshpass

    - name: Configure known hosts
      shell: bash
      run: |
        echo "${{ inputs.bunny-ssh-knownhosts }}" >> ~/.ssh/known_hosts

