name: cdn-upload-firmware
description: Uploads firmware partitions and merged binaries to CDN along with SHA256 checksums
inputs:
  bunny-stor-host:
    description: Bunny SFTP Hostname
    required: true
  bunny-stor-username:
    description: Bunny SFTP Username
    required: true
  bunny-stor-password:
    description: Bunny SFTP Password
    required: true
  fw-version:
    description: Firmware version
    required: true
  board:
    description: 'Board to upload'
    required: true

runs:
  using: composite
  steps:
    - name: Download static filesystem partition
      uses: actions/download-artifact@v4
      with:
        name: firmware_staticfs
        path: .

    - name: Download firmware partitions
      uses: actions/download-artifact@v4
      with:
        name: firmware_build_${{ inputs.board }}
        path: .

    - name: Download merged firmware binary
      uses: actions/download-artifact@v4
      with:
        name: firmware_merged_${{ inputs.board }}
        path: .

    - name: Rename firmware binaries
      shell: bash
      run: |
        mv OpenShock_*.bin firmware.bin

    - name: Generate SHA256 checksums
      shell: bash
      run: |
        find . -type f -name '*.bin' -exec md5sum {} \; > hashes.md5.txt
        find . -type f -name '*.bin' -exec sha256sum {} \; > hashes.sha256.txt

    - name: Upload artifacts to CDN
      shell: bash
      run: |
        mkdir -p upload
        mv *.bin upload/
        mv hashes.*.txt upload/
        sshpass -p "${{ inputs.bunny-stor-password }}" scp -r upload/ ${{ inputs.bunny-stor-username }}@${{ inputs.bunny-stor-host }}:/${{ inputs.fw-version }}/${{ inputs.board }}