on:
  push:
    branches:
      - master
      - beta
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:
    branches:
      - master
      - beta
      - develop
    types: [opened, reopened, synchronize]
  workflow_dispatch: # Manually invoked by user.

name: ci-build

jobs:
  getvars:
    uses: ./.github/workflows/get-vars.yml

  build:
    needs: getvars
    uses: ./.github/workflows/build-all.yml
    with:
      fw-version: ${{ needs.getvars.outputs.version }}
      board-matrix: ${{ needs.getvars.outputs.board-matrix }}

  publish:
    if: ${{ needs.getvars.outputs.should-deploy == 'true' }}
    needs: [getvars, build]
    uses: ./.github/workflows/publish-all.yml
    with:
      version: ${{ needs.getvars.outputs.version }}
      release-channel: ${{ needs.getvars.outputs.release-channel }}
      is-prerelease: ${{ needs.getvars.outputs.release-channel != 'stable' }}
      board-list: ${{ needs.getvars.outputs.board-list }}
      board-matrix: ${{ needs.getvars.outputs.board-matrix }}
      release-notes: ${{ needs.getvars.outputs.release-notes }}
