on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'
  workflow_dispatch:

name: ci-tag
run-name: 'ci-tag: ${{ github.ref_name }}'

jobs:
  # Read platformio.ini and extract all specific targets. See the referenced file for more info.
  getvars:
    uses: ./.github/workflows/get-vars.yml

  build:
    needs: getvars
    uses: ./.github/workflows/build-all.yml
    with:
      fw-version: ${{ needs.getvars.outputs.version }}
      board-matrix: ${{ needs.getvars.outputs.board-matrix }}

  publish:
    needs: [getvars, build]
    uses: ./.github/workflows/publish-all.yml
    with:
      version: ${{ needs.getvars.outputs.version }}
      release-channel: ${{ contains(github.ref_name, '-') && 'stable' || 'beta' }}
      is-prerelease: ${{ contains(github.ref_name, '-') }}
      board-list: ${{ needs.getvars.outputs.board-list }}
      board-matrix: ${{ needs.getvars.outputs.board-matrix }}
      release-notes: ${{ needs.getvars.outputs.release-notes }}
